using UnityEngine;
using System.Collections;

public enum TileMechanic{
    NO_MECHANIC,
    PLAYER_ATTACK_SUPPORT,
    PLAYER_RETREAT_LINE,
    PLAYER_SPAWN_REINFORCEMENT,
    PLAYER_SPAWN_MAIN,
    ENEMY_RETREAT_LINE,
    ENEMY_SPAWN_REINFORCEMENT,
    ENEMY_SPAWN_SUPPORT,
}
